### ISSUE TITLE
Bug Report - UI Change for Landing Page

### ISSUE THREAD

**Issue by Abhishek-Mallick** [devhub-ai/devhub#30]
**Describe the bug**
The current landing page does not reflect the DevHub branding and lacks configured routes and templates, resulting in a disjointed user experience.

**To Reproduce**
1. Navigate to the landing page of DevHub.
2. Observe the current UI elements and layout.
3. Note the absence of DevHub-centric branding and configured routes.

**Expected behavior**
The landing page should feature a cohesive design that aligns with the DevHub brand, including properly configured routes and templates that enhance user navigation.

**Screenshots**
![image](https://github.com/user-attachments/assets/66cabe21-89c9-4c36-b070-0e689e580dde)
![image](https://github.com/user-attachments/assets/87e2fb91-a7bc-40c7-a303-bd7209ea8a84)

**Viable Solution**
Implement a new UI design for the landing page that incorporates DevHub branding elements. Configure routes and templates to improve navigation and user engagement.

**Comment by Ashu1823** [comment]
Hi..
Intrested for contribution.

**Comment by Abhishek-Mallick** [comment]
Assigned it to you @Ashu1823
Check [this](https://github.com/devhub-ai/devhub/blob/main/.github/CONTRIBUTING.md) out to get started

**Comment by Ashu1823** [comment]
Okay.. Thanks for assigning.. Is there any UX file that I can refer to.

**Comment by deepraj21** [comment]
Sure here is the brief detail of the work you need to do.
[landing-page-enhancement.txt](https://github.com/user-attachments/files/17219788/landing-page-enhancement.txt)
Feel free to ask us on the Discord server for any type of clarification or help.

**Comment by Ashu1823** [comment]
Okay @deepraj21 thanks..
