### ISSUE TITLE
✨ Feature Request - Mobile Responsiveness & Enhanced Login/Signup

### ISSUE THREAD

**Issue by Abhishek-Mallick** [devhub-ai/devhub#31]
**Is this feature request related to a problem with DevHub? Please describe.**  
The current login and signup pages are not responsive on mobile devices, limiting accessibility for users on smartphones. The signup process is currently restricted to username only, which could be improved by allowing email signups with OTP verification.

**Describe the solution needed**  
- Make both `/login` and `/signup` pages fully responsive for mobile devices.
- Enhance the signup process to allow users to register using either their username or email address.
- Implement an OTP verification system using a Python package to send emails for email-based signups.
- Modify the login process to accept either "username or email id" along with "password".

**Describe alternatives considered**  
Currently, users can only sign up with a username, which may not be ideal for everyone. An alternative could be allowing social media logins; however, this may complicate the user experience.

**How will this feature improve DevHub?**  
These enhancements will significantly improve user experience by making it easier for students to access the platform on mobile devices and providing more flexible options for account creation and login.

**Additional context**  
Consider looking into responsive design frameworks (like Bootstrap) and email verification libraries (like Flask-Mail for implementation.

**Comment by jasminepvo** [comment]
Hi Abhishek, 

I’ve been looking into the issue regarding the login and signup pages not being responsive and the enhancements for email signups with OTP verification. To ensure the changes are more manageable and can be tackled effectively, I would like to suggest breaking this issue into two separate tickets:

1. UI Responsiveness: An issue focused solely on making the /login and /signup pages fully responsive for mobile devices. This can include working with responsive design frameworks such as Bootstrap or media queries for optimal mobile layouts.
2. Signup Process Enhancement: A separate issue addressing the functionality changes, like allowing email-based signups, implementing OTP verification using a Python package like Flask-Mail, and modifying the login process to accept either a username or email.

This would help contributors focus on specific areas (UI vs. functionality) and allow for clearer testing and review of each component. Let me know your thoughts!

Cheers,
Jasmine Vo

**Comment by Abhishek-Mallick** [comment]
well-thought-out suggestion! 👍 Breaking down the issue into separate UI and functionality components makes a lot of sense.

**Comment by Abhishek-Mallick** [comment]
Issue further divided into https://github.com/devhub-ai/devhub/issues/34 and https://github.com/devhub-ai/devhub/issues/35

Closing this issue for now
