### ISSUE TITLE
Feature: Responsive UI for Login/Signup Pages

### ISSUE THREAD

**Issue by Abhishek-Mallick** [devhub-ai/devhub#34]
## Feature Request

**Is your feature request related to a problem you're trying to solve with Devhub? Please describe.**
The current login and signup pages are not responsive on mobile devices, limiting accessibility for users on smartphones.

**Describe the solution you'd like**
- Make both `/login` and `/signup` pages fully responsive for mobile devices
- Implement responsive design using Bootstrap or media queries
- Ensure optimal layouts for various mobile screen sizes
- Adapt form elements and buttons for better mobile interaction

**Describe alternatives you've considered**
Creating separate mobile-specific routes was considered but responsive design is more maintainable and follows best practices.

**How would this feature improve Devhub?**
This enhancement will significantly improve user experience by making it easier for students to access the platform on mobile devices.

**Additional context**
- Focus on Bootstrap's responsive grid system if using Bootstrap
- Ensure consistent rendering across different mobile browsers
- Consider touch-friendly input elements

**Comment by jasminepvo** [comment]
Happy to take this on!

**Comment by Abhishek-Mallick** [comment]
Sure.. assigned!

**Comment by DanielAgbeni** [comment]
Has this been fixed aleady?
@Abhishek-Mallick

**Comment by deepraj21** [comment]
@jasminepvo please let us know if you are still working on this issue.
