### ISSUE TITLE
Feature: Email Signup with Flask-Mail OTP Verification

### ISSUE THREAD

**Issue by Abhishek-Mallick** [devhub-ai/devhub#35]
## Feature Request

**Is your feature request related to a problem you're trying to solve with Devhub? Please describe.**
The signup process is currently restricted to username only, which could be improved by allowing email signups with OTP verification.

**Describe the solution you'd like**
- Enhance the signup process to allow registration using either username or email
- Implement OTP verification system using Flask-Mail for email-based signups
- Modify the login route to accept either username or email along with password
- Update SQLAlchemy models to include email field and verification status

**Describe alternatives you've considered**
Social media logins were considered but may complicate the user experience. Email verification provides a good balance of security and usability.

**How would this feature improve Devhub?**
This will provide more flexible options for account creation and login, enhancing user convenience while maintaining security.

**Additional context**

## Are you willing to resolve this issue by submitting a Pull Request?
- Use Flask-Mail for handling email functionality
- Implement rate limiting for OTP generation using Flask-Limiter
- Consider using Flask-Security for additional auth features if needed
- Update Flask routes to handle new email-based login logic

**Comment by BlazeBoy22** [comment]
hey i want to work on this feature enhancement , i already have experience with nodemailer
so can you assign me this issue

**Comment by Abhishek-Mallick** [comment]
Sure.. assigned!
