### ISSUE TITLE
Responsiveness of Landing page

### ISSUE THREAD

**Issue by deepraj21** [devhub-ai/devhub#37]
**Describe the bug**
The landing page is not responsive in mobile and tab mode. 

**To Reproduce**
1. Run the client side
2. open the localhost:5173
3. Inspect the page
4. See responsiveness error

**Expected behavior**
- The navbar should show the logo and toggle for dark/light mode.
- Add gaps in Hero Section and reduce the heading and content gap
- Add margin left for the features section and add Feature heading at top
-  Add margin all around in FAQ
- Remove the dark effect at the footer

**Screenshots**
![image](https://github.com/user-attachments/assets/4be9d02a-5927-4e1c-a22d-d3c493ed490d)
![image](https://github.com/user-attachments/assets/adaeab0e-1e3a-4613-9b72-c03a1d39c37b)
![image](https://github.com/user-attachments/assets/d0be0ab5-5e33-4f5b-80bd-e7257f0aa17d)
![image](https://github.com/user-attachments/assets/e82f3783-c03d-4dde-b0d0-77d945b36eb2)
![image](https://github.com/user-attachments/assets/6280722a-d2c6-48be-b0a8-5332d821b8fb)

**Comment by spartanns** [comment]
I'd be interested to work on this.

**Comment by deepraj21** [comment]
ok, you can work on this issue.

**Comment by spartanns** [comment]
I have a couple of questions, though:
1) In Hero section, by "heading" you mean the feature title? So a gap between feature title and its content?
2) In Features section, again, by heading you meant the feature title on top? Or should I add a heading to the section that says "Feature"?
3) Is the following picture what you had in mind for the navbar?
![Screenshot from 2024-10-06 14-58-07](https://github.com/user-attachments/assets/f0e6e827-bb1d-440d-9c1f-d196b032ea3d)

**Comment by deepraj21** [comment]
Yeah, the above image seems good.

Some changes I want you to make are:
1. You can remove the middle icon and add two more icons with features(scrolling to that section) and GitHub.[for mobile responsive].
1. yes add a heading with "features" written.
2. in the hero section make the components visible (like the globe, images are not visible due to its parent component height. You can add some padding and height according to the good UX)

Additional:
Can you also add the theme mode to the desktop model? (you can find the toggle in Components/Theme) ?

**Comment by spartanns** [comment]
Take a look, and let me know what other changes you would like:
[Untitled Video October 7, 2024 2_57 PM.webm](https://github.com/user-attachments/assets/c5269274-a0bf-46bc-8732-93491880ff4f)

**Comment by deepraj21** [comment]
All the mentioned issues are addressed and looks cool but can you look into the last part (faq and footer section)

Specific issue
1. Width of faq should be reduced.(Keep 80% of the screen for mobile mode)
2. The black color over the footer corners should be fixed.

**Comment by spartanns** [comment]
I moved the ellipse to the bottom, so only the top of the page has dark corners now
![Screenshot from 2024-10-10 14-51-07](https://github.com/user-attachments/assets/9a664bd2-99c1-470d-81f5-a9aba48a5555)

I reduced the FAQ grid width, and centered it on x axis
![Screenshot from 2024-10-10 15-03-13](https://github.com/user-attachments/assets/9ed7a417-f972-4a41-843c-a86f498e4c43)

**Comment by deepraj21** [comment]
Ok looks good
you can raise the PR
