### ISSUE TITLE
Feature: Improve the UI of the chat screen

### ISSUE THREAD

**Issue by DanielAgbeni** [devhub-ai/devhub#39]
## Feature Request

The UI of the chat screen should be more user friendly with the chat bubble of the user on the right and the chat bubble of the AI on the left
And A better UX when waiting for the AI resposnse
![image](https://github.com/user-attachments/assets/23d57b1f-6980-4a46-9538-a9484d036c1e)

**Comment by DanielAgbeni** [comment]
Can I work on it?

**Comment by deepraj21** [comment]
Can you show some example design for the enhancement?
You can show some images or can describe it more.

**Comment by DanielAgbeni** [comment]
It should look similar to chat gpt

**Comment by DanielAgbeni** [comment]
Render the user's message immediately upon sending, then update the UI with the AI's response after completion.

**Comment by deepraj21** [comment]
Ok, you can do it.
Assigning

**Comment by DanielAgbeni** [comment]
Alright
