### ISSUE TITLE
Update the UI of profile section

### ISSUE THREAD

**Issue by deepraj21** [devhub-ai/devhub#44]
**Describe the bug**
Update the UI of the profile section which looks similar to leetcode profile section.

**To Reproduce**
1. Go to client
2. Run the client side
3. Go the profile 
4. See the section

**Current behavior**
1. The sidebar bottom part is moving up when coming to /profile
2. the sections are not in the cards.
3. Loading is showing instead of skeleton

**Screenshots**
![image](https://github.com/user-attachments/assets/2afd736a-707e-4825-8805-0e681121c714)
![image](https://github.com/user-attachments/assets/d39579a1-c8e9-4687-bcfd-3fb96332adfa)
![image](https://github.com/user-attachments/assets/075df50e-8997-46eb-82c0-3aeee9726a8f)

**Viable Solution**
1. fix the profile and logo at the bottom.
2. make the profile section look like leetcode profile.
3. adjust the various components of profile for a better UI/UX.
4. if initially data is not provided then show skeleton instead of loading...

**Additional context**

leetcode profile section:
![image](https://github.com/user-attachments/assets/273c580c-3330-47cd-89d1-00b840c8819a)

shadcn skeleton component link:
https://ui.shadcn.com/docs/components/skeleton

**Comment by DanielAgbeni** [comment]
Pls assign me

**Comment by deepraj21** [comment]
ok assigned.

**Comment by DanielAgbeni** [comment]
This Issue can be closed now
