### ISSUE TITLE
Feature: Add type check (validation) for username during signup

### ISSUE THREAD

**Issue by deepraj21** [devhub-ai/devhub#45]
## Feature Request

**Is your feature request related to a problem you're trying to solve with Devhub? Please describe.**
Add a type check during signup for username (should be alphanumeric, must be greater than 7 and less than 12 characters)

**Describe the solution you'd like**
When a user Signup then add a check whether the username is valid or not. (should be in the client side)

validation criteria:
1. must be alphanumeric
2. greater than 7 characters
3. less than 12 characters

If not valid then show the error below the input field what's missing or going wrong.

**Comment by MuhammedJaseemVK** [comment]
@deepraj21 Can you assign this issue to me? I would like to work on this

**Comment by deepraj21** [comment]
Ok assigning.
